DELETE FROM ${STGDB}.DEVICE_PURCHASED_WT2
WHERE LINE_OF_BUS_NUM = ${LINE_OF_BUS_NUM};

SELECT
     TMAT_ACCT_NUM
     ,LINE_OF_BUS_NUM
     ,DEVICE_STATUS_DT
     ,DEVICE_STATUS_CD
     ,MSISDN
     ,EQUIP_SERIAL_NUM
     ,ICCID
     ,DEVICE_PURCH_DT
     ,DEVICE_ACTIVATION_DT
     ,CNTL_EFF_DT
     ,CNTL_EXP_DT
     ,CURR_PREV_IND
     ,CURRENT_TIMESTAMP(0)
     ,CURRENT_TIMESTAMP(0)
FROM
   ${STGDB}.DEVICE_PURCHASED_WT2
WHERE LINE_OF_BUS_NUM = ${LINE_OF_BUS_NUM}



DELETE FROM ${STGDB}.DEVICE_PURCHASED_WT2
WHERE LINE_OF_BUS_NUM = ${LINE_OF_BUS_NUM};



UPDATE ${TRGDB}.DEV_PUR CORE
SET
CNTL_EXP_DT = (('${RUNDATE}'||'23:59:59') (TIMESTAMP(0) ,FORMAT 'YYYY-MM-DDHH:MI:SS')) - INTERVAL '1' DAY
,CURR_PREV_IND = 'P'
,LAST_UPD_DT = CURRENT_TIMESTAMP(0)
WHERE
	CORE.TMAT_ACCT_NUM = ${STGDB}.DEVICE_PURCHASED_WT2.TMAT_ACCT_NUM
AND CORE.LINE_OF_BUS_NUM = ${STGDB}.DEVICE_PURCHASED_WT2.LINE_OF_BUS_NUM
AND CORE.EQUIP_SERIAL_NUM = ${STGDB}.DEVICE_PURCHASED_WT2.EQUIP_SERIAL_NUM
AND CORE.CURR_PREV_IND = 'C'
AND CORE.LINE_OF_BUS_NUM = ${LINE_OF_BUS_NUM};


INSERT INTO ${TRGDB}.DEV_PUR
(
     TMAT_ACCT_NUM
     ,LINE_OF_BUS_NUM
     ,DEVICE_STATUS_DT
     ,DEVICE_STATUS_CD
     ,MSISDN
     ,EQUIP_SERIAL_NUM
     ,ICCID
     ,DEVICE_PURCH_DT
     ,DEVICE_ACTIVATION_DT
     ,CNTL_EFF_DT
     ,CNTL_EXP_DT
     ,CURR_PREV_IND
     ,INSERT_DT
     ,LAST_UPD_DT
)
SELECT
     TMAT_ACCT_NUM
     ,LINE_OF_BUS_NUM
     ,DEVICE_STATUS_DT
     ,DEVICE_STATUS_CD
     ,MSISDN
     ,EQUIP_SERIAL_NUM
     ,ICCID
     ,DEVICE_PURCH_DT
     ,DEVICE_ACTIVATION_DT
     ,CNTL_EFF_DT
     ,CNTL_EXP_DT
     ,CURR_PREV_IND
     ,CURRENT_TIMESTAMP(0)
     ,CURRENT_TIMESTAMP(0)
FROM
   ${STGDB}.DEVICE_PURCHASED_WT2
WHERE LINE_OF_BUS_NUM = ${LINE_OF_BUS_NUM}

;

